name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: ['7.4', '8.0', '8.1' ]
        
    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: Run PHP-CS-Fixer
      run: composer cs:check

    - name: Create env
      run: php qt core:env

    - name: Create app key
      run: php qt core:key --length=64

    - name: Run tests
      run: composer test
